-- Migration 184: AA-660 follow-up — a Verdict is asked once per (question wording, subject), and every
-- Verdict records which wording answered it.
--
-- decision_question.question_hash — md5 of kind + instructions + criteria, generated by the DB so the
--   app never has to reproduce JSON text formatting. A change of wording is a new hash: cached Verdicts
--   from the old wording are not reused, and the old Calibration Record no longer applies (Nghiệp, Q12).
-- decision_log.question_hash — the hash the Verdict was produced under.
-- decision_log.cached — true when the Verdict was served from an earlier Verdict (no Jev call, no cost).
-- Lookup index for the cache (subject, question, newest first).
-- Additive; existing rows are backfilled from the current wording (unchanged since 181–183).

BEGIN;

ALTER TABLE shared.decision_question
    ADD COLUMN IF NOT EXISTS question_hash TEXT
        GENERATED ALWAYS AS (md5(kind || '|' || instructions || '|' || coalesce(criteria::text, ''))) STORED;

ALTER TABLE shared.decision_log
    ADD COLUMN IF NOT EXISTS question_hash TEXT,
    ADD COLUMN IF NOT EXISTS cached BOOLEAN NOT NULL DEFAULT false;

UPDATE shared.decision_log l SET question_hash = q.question_hash
FROM shared.decision_question q
WHERE q.question_key = l.question_key AND l.question_hash IS NULL;

CREATE INDEX IF NOT EXISTS decision_log_cache_idx
    ON shared.decision_log (subject_key, question_key, created_at DESC);

INSERT INTO shared.schema_versions (version, applied_at, description)
VALUES ('184', now(), 'AA-660: decision_question.question_hash (generated), decision_log.question_hash + cached')
ON CONFLICT (version) DO NOTHING;

COMMIT;
